---
abstract: 'MediaRSS support for XML::FeedPP'
author:
  - 'Paul Driver <frodwith@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::More: 0
  Tie::IxHash: 0
  XML::FeedPP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-FeedPP-MediaRSS
requires:
  XML::FeedPP: 0
version: 0.02
